### ISSUE TITLE
repo not updated with code 

### ISSUE THREAD

**Issue by knitemblazor** [NavtejBagdy/iAI-internship#1]
clone and create the repo from https://github.com/shahkalp09/Internship

**Comment by knitemblazor** [comment]
@NavtejBagdy  update the repo

**Comment by NavtejBagdy** [comment]
Done sir

**Comment by knitemblazor** [comment]
multiple branches were there in the project please add em all @NavtejBagdy

**Comment by NavtejBagdy** [comment]
Hi Sir,

I'm in office at the moment, I had a call with Vidya Mudaliyar ma'am, she
said my onboarding process will be on Monday, so I again don't have my
laptop to work with. Could you please arrange for me to get access to bring
my laptop inside, or if that's not possible can I leave and work from home
today? As it's much easier and productive to work with my laptop and
already I haven't been able to work the last three times I came to office
because of not being able to bring my laptop inside.

Best Regards,
Navtej Bagdy

**Comment by knitemblazor** [comment]
yes @NavtejBagdy  please work from home do not wait for access if its taking that long

**Comment by NavtejBagdy** [comment]
> yes @NavtejBagdy  please work from home do not wait for access if its taking that long

Okay sir, leaving now. Will take me around one and half hours to reach home, will update the repo once I reach

**Comment by NavtejBagdy** [comment]
> multiple branches were there in the project please add em all @NavtejBagdy

Done sir
